---
- name: "Create rust tools directory"
  file:
    path: "/home/{{ssh.user}}/.cargo/bin"
    state: directory
    mode: 0755
    owner: "{{ ssh.user }}"
    group: "{{ ssh.user }}"

- name: "Download Rustup version {{rustup.version}}"
  get_url:
    url: "https://static.rust-lang.org/rustup/archive/1.22.1/x86_64-unknown-linux-gnu/rustup-init"
    dest: "/home/{{ ssh.user }}/.cargo/bin/rustup"
    checksum: "{{rustup.checksum}}"
    mode: "a+x"

- name: "Download Rust analyzer version {{analyzer.version}}"
  get_url:
    url: "https://github.com/rust-analyzer/rust-analyzer/releases/download/{{analyzer.version}}/rust-analyzer-linux"
    dest: "/home/{{ ssh.user }}/bin/rust-analyzer"
    checksum: "{{analyzer.checksum}}"
    mode: "a+x"
