---
- name: "Create rust tools directory"
  file:
    path: "/home/{{ssh.user}}/.cargo/bin"
    state: directory
    mode: 0755
    owner: "{{ ssh.user }}"
    group: "{{ ssh.user }}"

- name: "Download Rustup version {{rustup[arch].version}}"
  get_url:
    url: "https://static.rust-lang.org/rustup/archive/{{rustup[arch].version}}/{{arch}}-unknown-linux-gnu/rustup-init"
    dest: "/home/{{ ssh.user }}/.cargo/bin/rustup"
    checksum: "{{rustup[arch].checksum}}"
    mode: "a+x"
    owner: "{{ ssh.user }}"
    group: "{{ ssh.user }}"

- name: "Download Rust analyzer version {{analyzer[arch].version}}"
  get_url:
    url: "https://github.com/rust-analyzer/rust-analyzer/releases/download/{{analyzer[arch].version}}/rust-analyzer-{{arch}}-unknown-linux-gnu.gz"
    dest: "/home/{{ ssh.user }}/bin/rust-analyzer.gz"
    checksum: "{{analyzer[arch].checksum}}"
    mode: "a+x"
    owner: "{{ ssh.user }}"
    group: "{{ ssh.user }}"

- name: "Setup rust analyzer into executable path"
  shell: gunzip /home/{{ ssh.user }}/bin/rust-analyzer.gz
