---
- name: "Download & unpack Go archive."
  unarchive:
    src: "https://storage.googleapis.com/golang/go{{ versions.go }}.linux-amd64.tar.gz"
    dest: "/usr/local"
    remote_src: true
    creates: "/usr/local/go/bin/go"

- name: "Create Go directories"
  become: yes
  become_user: "{{ ssh_params.user }}"
  become_method: sudo
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "~/src/golang/bin"
    - "~/src/golang/src"
    - "~/src/golang/pkg"

- name: "Install glide"
  shell: "curl https://glide.sh/get | sh"
  args:
    creates: "~/src/golang/bin/glide"

- name: "Install gocode"
  shell: "go get -u github.com/nsf/gocode"
  args:
    creates: "~/src/golang/bin/gocode"
