- name: Configure SSH on the machine.
  hosts: desktop_machines
  remote_user: zee
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo

  vars_files:
    - vars/development-params.yml

  roles:
    - secure-ssh
  tags: ssh

- name: Install Docker
  hosts: desktop_machines
  remote_user: zee
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo

  vars_files:
    - vars/development-params.yml

  roles:
    - docker
  tags: docker

- name: Install development utilities.
  hosts: desktop_machines
  remote_user: zee
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo

  vars_files:
    - vars/development-params.yml
  roles:
    - devutils
  tags: devutils

- name: Install clojure & prepare development.
  hosts: desktop_machines
  remote_user: zee
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo

  vars_files:
    - vars/development-params.yml
  roles:
    - clojure
  tags: clojure

- name: Install scala(sbt)
  hosts: desktop_machines
  remote_user: zee
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo

  vars_files:
    - vars/development-params.yml
  roles:
    - scala
  tags: scala


- name: Install golang, prepare env & fetch some utils.
  hosts: desktop_machines
  remote_user: zee
  gather_facts: yes
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin:/home/zee/src/golang/bin"
    GOROOT: "/usr/local/go"
    GOPATH: "/home/zee/src/golang"
    GOBIN: "/home/zee/src/golang/bin"
  vars_files:
    - vars/development-params.yml
  roles:
    - golang
  tags: golang
