- name: Configure SSH on the machine.
  hosts: desktop_machines
  remote_user: zee
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo

  vars_files:
    - vars/development-params.yml

  roles:
    - secure-ssh
  tags: ssh

- name: Install Docker
  hosts: desktop_machines
  remote_user: zee
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo

  vars_files:
    - vars/development-params.yml

  roles:
    - docker
  tags: docker

- name: Install development utilities.
  hosts: desktop_machines
  remote_user: zee
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo

  vars_files:
    - vars/development-params.yml
  roles:
    - devutils
  tags: devutils

- name: Install clojure & prepare development.
  hosts: desktop_machines
  remote_user: zee
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo

  vars_files:
    - vars/development-params.yml
  roles:
    - clojure
  tags: clojure

- name: Install golang, prepare env & fetch some utils.
  hosts: desktop_machines
  remote_user: zee
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo

  vars_files:
    - vars/development-params.yml
  roles:
    - golang
  tags: golang
