- name: "Configure Ubuntu 20.04 server as everyday machine."
  hosts: laptop
  gather_facts: no
  vars_files:
    - vars/laptop.yml
    - vars/vault.yml
  roles:
    - meta
    #- { role: secure-ssh, become: yes, become_user: root, become_method: sudo}
    #- { role: purge-snap, become: yes, become_user: root, become_method: sudo}
    #- { role: zsh, become: yes, become_user: root, become_method: sudo}
    - { role: gui-base, become: yes, become_user: root, become_method: sudo}
    #- { role: dev-base, become: yes, become_user: root, become_method: sudo}
    #- { role: gui-extras, become: yes, become_user: root, become_method: sudo}
    #- { role: docker, become: yes, become_user: root, become_method: sudo}

    #----Programming Languages----#
    #- { role: clojure, become: yes, become_user: root, become_method: sudo}
    #- { role: go, become: yes, become_user: root, become_method: sudo}
    #- { role: haskell, become: yes, become_user: root, become_method: sudo}
    #- { role: javascript, become: yes, become_user: root, become_method: sudo}
    #- { role: racket, become: yes, become_user: root, become_method: sudo}
    #- { role: rust, become: yes, become_user: root, become_method: sudo}

    #----Emacs----#
    #- { role: emacs, become: yes, become_user: root, become_method: sudo}
