---
- name: "Is firefox there?"
  become: yes
  become_user: "{{ ssh.user }}"
  stat:
    path: "/home/{{ ssh.user }}/bin/firefox/firefox"
  register: firefox_installed
- name: "Download & verify firefox."
  get_url:
    url: "https://ftp.mozilla.org/pub/firefox/releases/80.0.1/linux-x86_64/en-US/firefox-80.0.1.tar.bz2"
    dest: "/tmp/ffx.tar.bz2"
    checksum: "sha256:3ac0c9c4454647ce986bbe6f3567b0e1de5c0719ed6b6627344292c581a2afd3"
    mode: "0755"
    owner: "{{ ssh.user }}"
    group: "{{ ssh.user }}"
  when: firefox_installed.stat.exists == false
- name: "Add to local bin folder"
  unarchive:
    src: "/tmp/ffx.tar.bz2"
    dest: "/home/{{ ssh.user }}/bin"
    remote_src: yes
  when: firefox_installed.stat.exists == false
