---
- name: "Detect currently installed CLJ cli version"
  shell: clojure --help | grep -c '{{clojure.version}}'
  register: clj_version_matching
  ignore_errors: true

- name: "Install Clojure CLI"
  get_url:
    url: "https://download.clojure.org/install/linux-install-{{clojure.version}}.sh"
    dest: "/tmp/install-clj"
    checksum: "{{clojure.checksum}}"
    mode: "a+x"
    owner: "{{ ssh.user }}"
    group: "{{ ssh.user }}"
  when: clj_version_matching.stdout == '0'

- name: "Run Clojure installer"
  become: yes
  become_user: "root"
  command: "/tmp/install-clj"
  when: clj_version_matching.stdout == '0'

- name: "Install clj-kondo."
  get_url:
    url: "https://github.com/borkdude/clj-kondo/releases/download/v{{kondo.version}}/clj-kondo-lsp-server-{{kondo.version}}-standalone.jar"
    dest: "/home/{{ ssh.user }}/bin/clj-kondo-lsp"
    checksum: "{{kondo.checksum}}"
    mode: "a+x"
    owner: "{{ ssh.user }}"
    group: "{{ ssh.user }}"
