---
- name: "Install latest OpenJDK 11."
  apt:
    name:
      - openjdk-11-jre
    update_cache: yes
    state: latest

- name: "Install latest leiningen."
  get_url:
    dest: "/home/{{ ssh.user }}/bin/lein"
    url: "https://raw.github.com/technomancy/leiningen/stable/bin/lein"
    mode: "a+x"

- name: "Install Clojure CLI"
  get_url:
    url: "https://download.clojure.org/install/linux-install-{{clojure.version}}.sh"
    dest: "/tmp/install-clj"
    checksum: "{{clojure.checksum}}"
    mode: "a+x"

- name: "Run Clojure installer"
  become: yes
  become_user: "root"
  command: "/tmp/install-clj"

- name: "Install clj-kondo."
  get_url:
    url: "https://github.com/borkdude/clj-kondo/releases/download/v{{kondo.version}}/clj-kondo-lsp-server-{{kondo.version}}-standalone.jar"
    dest: "/home/{{ ssh.user }}/bin/clj-kondo-lsp"
    checksum: "{{kondo.checksum}}"
    mode: "a+x"
