---
- include: user.yml
- name: Harden SSHD configuration.
  template:
    src: "sshd_config.j2"
    dest: "/etc/ssh/sshd_config"
    owner: root
    group: root
    mode: 0644

-  name: SSH service reload
   command: /bin/true
   notify:
     - Restart SSH service
