---
- name: Add sbt repository key
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 642AC823

- name: Add sbt repository
  apt_repository:
    repo: deb https://dl.bintray.com/sbt/debian /
    state: present
    filename: 'sbt'

- name: Install latest version of sbt engine.
  apt:
    name:
      - sbt
    update_cache: yes
    state: latest
