- name: "Fetch pyenv"
  become: yes
  become_user: "{{ ssh.user }}"
  git:
    repo: "https://github.com/pyenv/pyenv.git"
    dest: "~/.pyenv"
    accept_hostkey: true

- name: Install poetry and linting packages
  pip:
    name:
      - poetry
      - black
      - isort
      - mypy
