---
- name: Install ssl transport for apt.
  apt:
    name: apt-transport-https
    update_cache: yes
    state: latest

- name: Add docker repository key
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D

- name: Add docker repository
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo ubuntu-xenial main
    state: present
    filename: 'docker'

- name: Install latest version of the docker engine.
  apt:
    name:
      - docker-engine
    update_cache: yes
    state: latest

- name: Add deploy user to the docker group.
  user:
    name: "{{ ssh_params.user }}"
    groups: docker
    append: yes

- name: Configure the docker daemon.
  lineinfile:
    dest: "/lib/systemd/system/docker.service"
    regexp: "^ExecStart"
    line: "ExecStart=/usr/bin/dockerd {{ docker_params.dns }} -s {{ docker_params.storage_driver }}"
  notify: "Restart Docker"
